// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: maven-intro
:page-layout: guide
:page-duration: 20 minutes
:page-description: Building and testing a simple web application using Maven and Open Liberty
:page-tags: ['Maven', 'Getting Started']
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
= Building a web application with Maven

You’ll explore how to build a simple web application and test it by using Maven and Open Liberty.

== What you'll learn

You will work with an application project that is a simple servlet application and returns a simple response of `Hello! How are you today?`.

You will learn how to build and test this application project with an Open Liberty server by using Maven and the `liberty-maven-plugin` plug-in.

include::{common-includes}/gitclone.adoc[]

== Creating a Maven web application project

You first create the web project structure by following the Maven standard directory structure. Using the standard directory structure saves you from customizing the Maven Project Object Model (POM) build definition file later.

The current directory of the project has a POM file of `pom.xml` that describes the project build definition. All application source goes in the `src/main` directory. The test source goes in the `src/test` directory. The Open Liberty server configuration file of `server.xml` goes in the `src/main/liberty/config` directory.

The following diagram is an overview of the project directory structure:

    └── src
        ├── main
        │  └── java
        │  └── resources
        │  └── webapp
        │  └── liberty
        │         └── config
        └── test
            └── java

Other ways exist to quickly create the project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator] accelerator or the Maven https://github.com/WASdev/ci.maven#liberty-archetype-webapp[liberty-archetype-webapp] archetype.

== Building the project POM file

Before you can build the project, you create the `pom.xml` file. The POM file starts with a root `<project>` element that is followed by the POM version, which is always 4.0.0; the project coordinates; the project dependencies; and the build plug-in configuration.

The project coordinates consist of a group ID (`groupId`), an artifact ID (`artifactId`), a version (`version`), and the packaging for the POM (`packaging`). For a web application project, the value of the `packaging` field is `war` so that the project output artifact is a WAR file.

In the `<properties/>` element, the project compile level is set to `1.8` and the project source file encoding is set to `UTF-8`.

In the `<dependencies/>` element, include the `javax.servlet-api` dependency for compiling the HelloServlet class. Also, include the Apache `commons-httpclient` and `junit` dependencies for compiling and running the integration test EndpointIT class. 

By default, all dependencies are scoped to `compile` and bundled in the `WEB-INF/lib` path inside the WAR file. If the dependencies are provided by the server runtime, set the scope to `provided`. Similarly, set the scope for the test dependencies to `test`.

The `<finalName/>` element can be used to strip the version string from the project output artifact file name. The default is `${project.artifactId}-${project.version}` if the `<finalName>` element is not specified.

[source, xml]
----
include::start/pom.xml[]
----

=== Configuring the plug-ins for your Maven web application project
In the `<build/>` element, you are going to configure the plug-ins that build this project.

The `liberty-maven-plugin` plug-in installs the Liberty runtime, creates the server, and copies the project WAR file to the server apps directory as a loose application configuration file. During the integration-test phase of the Maven build, the plug-in starts the server before any integration test is run and stops the server after all the integration tests are completed. The plug-in execution configuration is inherited from the parent https://github.com/WASdev/ci.maven/blob/master/docs/parent-pom.md[liberty-maven-app-parent] POM file. This file defines the plug-in management for the liberty-maven-plugin goal execution bindings to the Maven build lifecycle in the `<pluginManagement/>` element. These configuration settings can be overridden in the project POM file if needed. Add the following `<parent/>` element to the project POM file:

[source, xml]
----
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.wasdev.wlp.maven.parent</groupId>
        <artifactId>liberty-maven-app-parent</artifactId>
        <version>2.0</version>
    </parent>
----

In this project, you will provide the `<assemblyArtifact/>` configuration element to install the  17.0.0.2 Liberty webProfile7 runtime from Maven Central. You will also provide the `<include/>` configuration element to create a Liberty `usr` type server package for this project. You will override the package-server execution to use a different output directory so that you can run the `mvn package` command with a running Liberty test server. For more information about the plug-in, see http://github.com/WASdev/ci.maven#liberty-maven-plugin.

[source, xml]
----
   <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            ...
            <plugin>
                <groupId>net.wasdev.wlp.maven.plugins</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>2.0</version>
                <configuration>
                    <assemblyArtifact>
                        <groupId>com.ibm.websphere.appserver.runtime</groupId>
                        <artifactId>wlp-webProfile7</artifactId>
                        <version>17.0.0.2</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <serverName>${project.artifactId}Server</serverName>
                    <include>usr</include>
                </configuration>
                <executions>
                    <execution>
                        <id>package-server</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package-server</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/wlp-package</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            ...
        </plugins>
	</build>  
----             

The maven-failsafe-plugin plug-in runs any integration test classes when the class name ends with IT. These integration test classes are run during the integration-test phase of the build after the WAR file is created. Test classes with a name that ends in TEST are unit test classes. The maven-surefire-plugin plug-in runs these test classes during the test phase of the build. If your test classes don’t follow the naming convention, configure both the Maven failsafe plug-in (maven-failsafe-plugin) and the Maven surefire plug-in (maven-surefire-plugin).

The version of the maven-war-plugin plug-in is overridden to 3.1.0 and the project `pom.xml` file is excluded in the WAR file output. Starting in 3.0.0 the default value has changed the failOnMissingWebXml configuration parameter for this plug-in was changed from `true` to `false` to allow a WAR project without a web.xml metadata file.

[source, xml]
----
   <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <packagingExcludes>pom.xml</packagingExcludes>
                </configuration>
            </plugin>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

== Creating the application

When the HelloServlet class is called, it responds back with `Hello! How are you today?`. The servlet URL pattern configuration is injected through the `@WebServlet` annotation in the class:

`src/main/java/sample/hello/HelloServlet.java`:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/hello/HelloServlet.java[tags=**;!comment]
----

The welcome page HTML file for the web project contains a link to the Hello servlet.

`src/main/webapp/index.html`:

[source,html]
----
include::finish/src/main/webapp/index.html[tags=**;!comment]
----

The deployment descriptor for the web application defines the list of welcome page files.

`src/main/webapp/WEB-INF/web.xml`:

[source,xml]
----
include::finish/src/main/webapp/WEB-INF/web.xml[]
----

The integration EndpointIT test invokes the HelloServlet class and verifies the return response.

`src/test/java/io/openliberty/guides/hello/it/EndpointIT.java`:

[source,java]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=**;!comment]
----

== Creating the Liberty server configuration

Create the `src/main/liberty/config/server.xml` file to provide the configuration to the Liberty server. The server is configured to run the `servlet-3.1` runtime. The server HttpEndpoint class and the servlet web application are also configured.

[source,xml]
----
include::finish/src/main/liberty/config/server.xml[]
----

include::{common-includes}/mvnbuild.adoc[]

== Congratulations! You're done!

You built and tested a web application project with an Open Liberty server by using Maven.

include::{common-includes}/finish.adoc[]
