// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: maven-intro
:page-layout: guide
:page-duration: 20 minutes
:page-description: Building and testing a simple web application using Maven and Open Liberty
:page-tags: ['Maven', 'Getting Started']
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
= Building a web application with Maven

Learn how to build and test a simple web application using Maven and Open Liberty.

== What you'll learn

You will learn how to configure a simple web servlet application using Maven and the Liberty Maven plugin (`liberty-maven-plugin`). When you compile and build the application code, Maven will download and install Open Liberty. When you run the application, Maven will run the application on an Open Liberty server.

When you have created a Maven build definition file (`pom.xml`) for the project and tested that it works, you will create a simple test that Maven can run to automatically test that the application runs.

When you run the application, a web page is displayed with a link. When you click the link, the servlet returns a simple response of `Hello! How are you today?`.


include::{common-includes}/gitclone.adoc[]

== Creating a simple application

The simple web application that we will build is provided for you in the `start` directory so that you can focus on learning about Maven. The application uses the standard Maven directory structure. Using the standard directory structure saves you from customizing the `pom.xml` file later. 

All the application source code, including the Open Liberty server configuration, `server.xml`, is in the `src/main` directory:

    └── src
        └── main
           └── java
           └── resources
           └── webapp
           └── liberty
                  └── config

== Installing Maven

Now you're ready to install Maven (if you haven't already). https://maven.apache.org/download.cgi[Download the binary zip or tar.gz file] and then follow the https://maven.apache.org/install.html[installation instructions for your operating system] to extract the ZIP file and add the `bin` directory (which contains the `mvn` command) to the `PATH` on your computer.

Test that Maven is installed by running the following command in a terminal:

----
mvn -v
----

If Maven is installed properly, you should see information about the Maven installation similar to this:

----
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: /Applications/Maven/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
----


== Creating the project POM file

Before you can build the project you define the Maven Project Object Model (POM) file, the `pom.xml`. Because the POM can look a bit daunting in full, we'll create it a section at a time.

Create the `pom.xml` file in the current directory (at the same level as the `src` directory):

[source,xml,indent=0]
----
include::finish/pom.xml[tags=**;!*]
----

The `pom.xml` file starts with a root `<project />` element and `<modelversion />`, which is always set to `4.0.0`. The `<parent />` element specifies that the Liberty Maven plugin will be used by Maven to build the Liberty-specific parts of this application.


Add the project coordinates of the sample application after the `<parent />` element:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=coordinates]
----

The project coordinates describe the name and version of the application. The `artifactId` gives a name to the web application project, which is used to name the output files that are generated by the build (e.g. the WAR file) and the Open Liberty server that is created. The value of the `packaging` field is `war` so that the project output artifact is a WAR file.

Specify the encoding and version of Java that Maven should use to compile the application source code:

(TODO: add here also the values for the server.xml)

[source,xml,indent=0]
----
include::finish/pom.xml[tags=properties]
----

Add details of the dependency that the web application needs in order to compile:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=dependencies;!dependencies_test]
----

The `HelloServlet.java` class depends on `javax.servlet-api` to compile. The dependency is set to `provided`, which means that the dependency is in the server runtime and doesn't need to be packaged by the application.

(TODO: Is that true?)

Configure the Maven plugins that build this project:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=build;!build_test]
----

Maven is very modular and extensible. Each capability is contained in a separate plugin. If you want to use a capability, you add that plugin to your POM file. In this `pom.xml` file:

* The `<finalName />` element removes the version string from the name of the output files that are generated by the build. If you don't specify the `<finalName />` element, the file name of the output files is `${project.artifactId}-${project.version}`.
* The  `<assemblyArtifact />` configuration element instructs Maven to install the Liberty `webProfile7` runtime verions `17.0.0.2` from Maven Central.
* You will also provide the `<include/>` configuration element to create a Liberty `usr` type server package for this project.
* You will override the package-server execution to use a different output directory so that you can run the `mvn package` command with a running Open Liberty test server. For more information about the plug-in, see http://github.com/WASdev/ci.maven#liberty-maven-plugin.

(TODO: Change the package names and version number for Open Liberty before publishing?)

include::{common-includes}/mvnbuild.adoc[]

== Testing the web application

One of the benefits of building an application with Maven is that Maven can be configured to run a set of tests, unit tests and integration tests. If the application does not pass the tests, the Maven build fails.

You can write tests for the individual units of code outside of a running application server, or they can be written to call the application server directly. In this example you will create a test that does the latter.

The web application in this project is very simple so we can write just one integration test that checks that the web page opens and the correct response is returned when the link is clicked.

Create the test class `src/test/java/io/openliberty/guides/hello/it/EndpointIT.java`:

[source,java,indent=0]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=**;!comment]
----

(TODO: Add explanation of test class here.)

The test class name ends in `IT` to indicate that it contains an integration test. (Test classes with a name that ends in TEST are unit test classes.)

In the `import` statements of this test class, you'll notice that the test has some new dependencies. Before the test can be compiled by Maven, you need to update the `pom.xml` to include these dependencies.

Add the following two `<dependency />` elements after the existing dependency in the `<dependencies />` section of the `pom.xml`:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=dependencies_test]
----

The Apache `commons-httpclient` and `junit` dependencies are needed to compile and run the integration test `EndpointIT` class. The scope for each of the dependencies is set to `test` because the libraries are needed only during the Maven build and do not needed to be packaged with the application.

(TODO: Is that the right explanation?)

Configure Maven to run the tests during the Maven build by adding the following `<plugin />` element after the existing plugins in the `<plugins />` section of the POM:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=build_test]
----

After Maven has created the WAR file that contains the web application, the `maven-failsafe-plugin` plugin runs any integration test classes (classes with names that end in `IT`).

The directory structure of the project should now look like this:

    └── src
        ├── main
        │  └── java
        │  └── resources
        │  └── webapp
        │  └── liberty
        │         └── config
        └── test
            └── java

You can now run the command `mvn install` to rebuild the application, including the test you've added, run the test, and see that the test passes. The Maven build takes a little longer than before the test existed, but expect to see the following information in the output:

(TODO: Output here. Will add when I've tested the instructions.)

The complete `pom.xml` should now look like this:

[source,xml,indent=0]
----
include::finish/pom.xml[**;*]
----

== Congratulations! You're done!

You built and tested a web application project with an Open Liberty server using Maven.

You can quickly create this project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator] accelerator or the Maven https://github.com/WASdev/ci.maven#liberty-archetype-webapp[liberty-archetype-webapp] archetype.

(TODO: Include these links here or elsewhere?)

TODO:

* Replace values in server.xml with variables for consistency with REST guide.
* Add more explanation of what the test is doing.
* Add more explanation throughout where applicable (see REST guide).
* Test the instructions work!

include::{common-includes}/finish.adoc[]
