// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: maven-intro
:page-layout: guide
:page-duration: 20 minutes
:page-description: Building and testing a simple web application using Maven and Open Liberty
:page-tags: ['Maven', 'Getting Started']
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
= Building a web application with Maven

Learn how to build and test a simple web application using Maven and Open Liberty.

== What you'll learn

You will learn how to configure a simple web servlet application using Maven and the Liberty Maven plugin (`liberty-maven-plugin`). When you compile and build the application code, Maven will download and install Open Liberty. When you run the application, Maven will run the application on an Open Liberty server.

When you have created a Maven build definition file (`pom.xml`) for the project and tested that it works, you will create a simple test that Maven can run to automatically test that the application runs.

When you run the application, a web page is displayed with a link. When you click the link, the servlet returns a simple response of `Hello! How are you today?`.


include::{common-includes}/gitclone.adoc[]

== Creating a simple application

The simple web application that we will build is provided for you in the `start` directory so that you can focus on learning about Maven. The application uses the standard Maven directory structure. Using the standard directory structure saves you from customizing the `pom.xml` file later. 

All the application source code, including the Open Liberty server configuration, `server.xml`, is in the `src/main` directory:

    └── src
        └── main
           └── java
           └── resources
           └── webapp
           └── liberty
                  └── config

== Installing Maven

Now you're ready to install Maven (if you haven't already). https://maven.apache.org/download.cgi[Download the binary zip or tar.gz file] and then follow the https://maven.apache.org/install.html[installation instructions for your operating system] to extract the ZIP file and add the `bin` directory (which contains the `mvn` command) to the `PATH` on your computer.

Test that Maven is installed by running the following command in a terminal:

----
mvn -v
----

If Maven is installed properly, you should see information about the Maven installation similar to this:

----
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: /Applications/Maven/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
----


== Creating the project POM file

Before you can build the project you define the Maven Project Object Model (POM) file, the `pom.xml`. Because the POM can look a bit daunting in full, we'll create it a section at a time.

Create the `pom.xml` file in the current directory (at the same level as the `src` directory):

[source,xml]
----
include::finish/pom.xml[tags=**;!*]
----

The `pom.xml` file starts with a root `<project />` element and `<modelversion />`, which is always set to `4.0.0`. The `<parent />` element specifies that the Liberty Maven plugin will be used by Maven to build the Liberty-specific parts of this application.


Add the project coodinates of the sample application after the `<parent />` element:

[source,xml]
----
include::finish/pom.xml[tags=coordinates]
----

The project coordinates describe the name and version of the application. For a web application project, the value of the `packaging` field is `war` so that the project output artifact is a WAR file.

(TODO: What are the other values for?)

Add a section to specify the encoding and version of Java that Maven should use to compile the application source code:

(TODO: add here also the values for the server.xml)

[source,xml]
----
include::finish/pom.xml[tags=properties]
----

Add details of the dependency that the web application needs in order to compile:

[source,xml]
----
include::finish/pom.xml[tags=dependencies;!dependencies_test]
----

The `HelloServlet.java` class depends on `javax.servlet-api` to compile. The dependency is set to `provided`, which means that the dependency is in the server runtime and doesn't need to be packaged by the application.





build details:



[source,xml]
----
include::finish/pom.xml[tags=build;!plugins]
----


The `<finalName/>` element can be used to strip the version string from the project output artifact file name. The default is `${project.artifactId}-${project.version}` if the `<finalName>` element is not specified.


include::{common-includes}/mvnbuild.adoc[]


== Testing the web application

The integration EndpointIT test invokes the HelloServlet class and verifies the return response.

`src/test/java/io/openliberty/guides/hello/it/EndpointIT.java`:

[source,java]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=**;!comment]
----

Updating the pom

test dependencies:

[source,xml]
----
include::finish/pom.xml[tags=dependencies_test]
----

Also, include the Apache `commons-httpclient` and `junit` dependencies for compiling and running the integration test EndpointIT class. Similarly, set the scope for the test dependencies to `test`.


dependencies details with added tests:

[source,xml]
----
include::finish/pom.xml[tags=dependencies]
----


test in build:

[source,xml]
----
include::finish/pom.xml[tags=build_test]
----


build details with added tests:

[source,xml]
----
include::finish/pom.xml[tags=build;!build_test]
----




== Building the project POM file







=== Configuring the plug-ins for your Maven web application project
In the `<build/>` element, you are going to configure the plug-ins that build this project.


In this project, you will provide the `<assemblyArtifact/>` configuration element to install the  17.0.0.2 Liberty webProfile7 runtime from Maven Central. You will also provide the `<include/>` configuration element to create a Liberty `usr` type server package for this project. You will override the package-server execution to use a different output directory so that you can run the `mvn package` command with a running Liberty test server. For more information about the plug-in, see http://github.com/WASdev/ci.maven#liberty-maven-plugin.

[source, xml]
----
   <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            ...
            <plugin>
                <groupId>net.wasdev.wlp.maven.plugins</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>2.0</version>
                <configuration>
                    <assemblyArtifact>
                        <groupId>com.ibm.websphere.appserver.runtime</groupId>
                        <artifactId>wlp-webProfile7</artifactId>
                        <version>17.0.0.2</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <serverName>${project.artifactId}Server</serverName>
                    <include>usr</include>
                </configuration>
                <executions>
                    <execution>
                        <id>package-server</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package-server</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>target/wlp-package</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            ...
        </plugins>
	</build>  
----             

The maven-failsafe-plugin plug-in runs any integration test classes when the class name ends with IT. These integration test classes are run during the integration-test phase of the build after the WAR file is created. Test classes with a name that ends in TEST are unit test classes. The maven-surefire-plugin plug-in runs these test classes during the test phase of the build. If your test classes don’t follow the naming convention, configure both the Maven failsafe plug-in (maven-failsafe-plugin) and the Maven surefire plug-in (maven-surefire-plugin).

The version of the maven-war-plugin plug-in is overridden to 3.1.0 and the project `pom.xml` file is excluded in the WAR file output. Starting in 3.0.0 the default value has changed the failOnMissingWebXml configuration parameter for this plug-in was changed from `true` to `false` to allow a WAR project without a web.xml metadata file.

[source, xml]
----
   <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <packagingExcludes>pom.xml</packagingExcludes>
                </configuration>
            </plugin>
            ...
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.19.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----









== Congratulations! You're done!

You built and tested a web application project with an Open Liberty server by using Maven.

include::{common-includes}/finish.adoc[]




The following diagram is an overview of the project directory structure:

    └── src
        ├── main
        │  └── java
        │  └── resources
        │  └── webapp
        │  └── liberty
        │         └── config
        └── test
            └── java

Other ways exist to quickly create the project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator] accelerator or the Maven https://github.com/WASdev/ci.maven#liberty-archetype-webapp[liberty-archetype-webapp] archetype.


TODO: Link to ci.maven docs?