// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: maven-intro
:page-layout: guide
:page-duration: 20 minutes
:page-description: Learn how to build and test a simple web application using Maven and Open Liberty
:page-tags: ['Maven', 'Getting Started']
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
= Building a web application with Maven

Learn how to build and test a simple web application using Maven and Open Liberty.

== What you'll learn

You will learn how to configure a simple web servlet application using Maven and the Liberty Maven plugin. When you compile and build the application code, Maven downloads and installs Open Liberty. When you run the application, Maven creates an Open Liberty server and runs the application on it. The application displays a simple web page with a link; when you click the link, the servlet returns a simple response of `Hello! How are you today?`.

One benefit of using Maven (or a similar build system like Gradle) is that, once you have defined the details of the project and any dependencies it has, Maven automatically handles downloading and installing any and all of the dependencies. You will create a Maven build definition file (`pom.xml`) for the web application project and use it to build the web application.

Another benefit of using Maven is that it can run automated tests on the application after building it. You could, of course, test your application manually by starting a server and pointing a web browser at the application URL. Automated tests are a much better approach though because Maven can easily re-run the same tests each time it builds the application and never gets bored. If the tests don't pass after you've made a change to the application, the build fails so you know that you need to fix your code.

When you have checked that the `pom.xml` builds the web application, you will then create a simple, automated test and configure Maven to run it after building the application.

include::{common-includes}/gitclone.adoc[]

== Creating a simple application

The simple web application that we will build using Maven and Open Liberty is provided for you in the `start` directory so that you can focus on learning about Maven. The application uses the standard Maven directory structure. Using the standard directory structure saves you from customizing the `pom.xml` file later. 

All the application source code, including the Open Liberty server configuration (`server.xml`), is in the `src/main/liberty/config` directory:

    └── src
        └── main
           └── java
           └── resources
           └── webapp
           └── liberty
                  └── config

== Installing Maven

Now you're ready to install Maven (if you haven't already). https://maven.apache.org/download.cgi[Download the binary zip or tar.gz file] and then follow the https://maven.apache.org/install.html[installation instructions for your operating system] to extract the ZIP file and add the `bin` directory (which contains the `mvn` command) to the `PATH` on your computer.

Test that Maven is installed by running the following command in a terminal:

----
mvn -v
----

If Maven is installed properly, you should see information about the Maven installation similar to this:

----
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T20:39:06+01:00)
Maven home: /Applications/Maven/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
----


== Creating the project POM file

Before you can build the project you define the Maven Project Object Model (POM) file, the `pom.xml`. Because the POM can look a bit daunting in full, we'll create it a section at a time.

Create the `pom.xml` file in the current directory (at the same level as the `src` directory):

[source,xml,indent=0]
----
include::finish/pom.xml[tags=whole;!*]
----

The `pom.xml` file starts with a root `<project />` element and `<modelversion />`, which is always set to `4.0.0`. The `<parent />` section of the POM specifies that Maven will use the Liberty Maven plugin (`liberty-maven-plugin`) to build the Liberty-specific parts of this application.

We'll now build up the `pom.xml` file, a section at a time in the space between the `</parent>` and `</project>` tags. Unless specified otherwise, add each of the following sections of XML code beneath the previous one. The `</project>` tag must be the last thing in the `pom.xml` file.

Add the project coordinates of the sample application:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=coordinates]
----

The project coordinates describe the name and version of the application. The `artifactId` gives a name to the web application project, which is used to name the output files that are generated by the build (e.g. the WAR file) and the Open Liberty server that is created. The value of the `packaging` field is `war` so that the project output artifact is a WAR file.

Specify the encoding and version of Java that Maven should use to compile the application source code:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=properties]
----

Add details of the dependency that the web application needs in order to compile:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=dependencies;!dependencies_test]
----

The `HelloServlet.java` class depends on `javax.servlet-api` to compile. Maven will download this dependency from the Maven Central repository using the `groupId`, `artifactId`, and `version` details that you provide here. The dependency is set to `provided`, which means that the API is in the server runtime and doesn't need to be packaged by the application.

Configure the Maven plugins that build this project:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=build;!build_test]
----

Maven is very modular and extensible. Each capability is contained in a separate plugin. If you want to use a capability, you add that plugin to your POM file.

Although the `<build />` section looks more complicated, it actually only gives details of three things:

* The first plugin is the Maven plugin for generating a WAR file as one of the output files.
* The second plugin is the Liberty Maven plugin which gives details of the name, version, and file type of Open Liberty runtime package which it will download from the public Maven repository.
** The `<include>usr</include>` line instructs Maven to create a Liberty `usr` type server package for this project.
** The `<outputDirectory />` element defines the name of the output directory so that you can run the `mvn package` command with a running test server and the output files will be put in the output directory instead of in the running server directory.

(TODO: Is this detail (the nested bullets) useful at this introductory level?)

include::{common-includes}/mvnbuild.adoc[]

== Testing the web application

One of the benefits of building an application with Maven is that Maven can be configured to run a set of tests. You can write tests for the individual units of code outside of a running application server (unit tests), or you can write them to call the application server directly (integration tests). In this example you will create a simple integration tests that checks that the web page opens and that the correct response is returned when the link is clicked.

When Maven runs the test, it starts a test server, runs the application, runs the test, and then stops the server.

Create the test class `src/test/java/io/openliberty/guides/hello/it/EndpointIT.java`:

[source,java,indent=0]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=**;!comment]
----

The test class name ends in `IT` to indicate that it contains an integration test. (Test classes with a name that ends in TEST are unit test classes.) 

The test code needs to know some information about the application in order to make requests. The server port and the application context root are key, and are dictated by the server configuration. While this information can be hardcoded, it is better to specify it in a single place like the Maven pom.xml file:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=serverProperties]
----

These Maven properties can then be passed to the Java test program as a series of system properties through the `maven-failsafe-plugin` plug-in.

[source,xml,indent=0]
----
include::finish/pom.xml[tags=systemProperties]
----

Getting the values to create a representation of the URL is then simple:

[source,xml,indent=0]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=URL]
----

The test method is indicated with the `@Test` annotation.

In the `try` block an HTTP `GET` request to the URL of the application returns a status code. If the response to the request includes the string `Hello! How are you today?`, the test passes. If that string is not in the response, the test fails.  The HTTP client then disconnects from the application.

[source,xml,indent=0]
----
include::finish/src/test/java/io/openliberty/guides/hello/it/EndpointIT.java[tags=clicklink]
----

In the `import` statements of this test class, you'll notice that the test has some new dependencies. Before the test can be compiled by Maven, you need to update the `pom.xml` to include these dependencies.

Add the following two `<dependency />` elements after the existing dependency in the `<dependencies />` section of the `pom.xml`:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=dependencies_test]
----

The Apache `commons-httpclient` and `junit` dependencies are needed to compile and run the integration test `EndpointIT` class. The scope for each of the dependencies is set to `test` because the libraries are needed only during the Maven build and do not needed to be packaged with the application.

Configure Maven to run the tests during the Maven build by adding the following `<plugin />` element after the existing plugins in the `<plugins />` section of the POM:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=build_test]
----

After Maven has created the WAR file that contains the web application, the `maven-failsafe-plugin` plugin runs any integration test classes (classes with names that end in `IT`).

The directory structure of the project should now look like this:

    └── src
        ├── main
        │  └── java
        │  └── resources
        │  └── webapp
        │  └── liberty
        │         └── config
        └── test
            └── java

You can now run the command `mvn install` to rebuild the application, including the test you've added, run the test, and see that the test passes. The Maven build takes a little longer than before the test existed, but expect to see the following information in the output:

[source,xml,indent=0]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openliberty.guides.hello.it.EndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.255 sec - in io.openliberty.guides.hello.it.EndpointIT

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the test detects a failure, change the response string in the servlet `src/main/java/io/openliberty/guides/hello/HelloServlet.java` so that it doesn't match the string that the test is looking for. Then re-run the Maven build and check that the test fails.

The complete `pom.xml` should now look like this:

[source,xml,indent=0]
----
include::finish/pom.xml[tags=whole]
----

== Congratulations! You're done!

You built and tested a web application project with an Open Liberty server using Maven.

You can quickly create this project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator] accelerator or the Maven https://github.com/WASdev/ci.maven#liberty-archetype-webapp[liberty-archetype-webapp] archetype.


include::{common-includes}/finish.adoc[]
